name: Create Pull Request

on:
  issue_comment:
    types: [created]

jobs:
  comment_triggered_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check Comment Content
        id: comment
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueComment = context.payload.comment.body.toLowerCase();
            if (issueComment.includes('/pull_request')) {
              console.log('Comment includes /run, triggering workflow...');
              return { runWorkflow: true };
            } else {
              console.log('Comment does not include /run, skipping workflow...');
              return { runWorkflow: false };
            }

      - name: Run Workflow If Triggered
        uses: actions/checkout@v2
        if: steps.comment.outputs.runWorkflow == 'true'
        run: |

      - name: Make Changes
        run: |
          # Make changes to the repository here
          echo "Hello, world!" > new-file.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Add new-file.txt via GitHub Actions"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        run: |
          PR_TITLE="Propose changes from external repository"
          PR_BODY="This pull request was created automatically from changes made in an external repository."
          PR_HEAD="main"  # Branch where changes are coming from
          PR_BASE="main"  # Branch where changes will be merged into

          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \

            -d '{
              "title": "'"$PR_TITLE"'",
              "body": "'"$PR_BODY"'",
              "head": "'"$PR_HEAD"'",
              "base": "'"$PR_BASE"'"
            }' \
            "https://api.github.com/repos/OWNER/REPO/pulls"
